#ifndef LABELS_H
#define LABELS_H

#include "colors.hpp"

#define LABEL_ERROR "[ERROR]"
#define LABEL_WARN  "[WARNING]"
#define LABEL_DEBUG "[DEBUG]"

#define ERROR COLOR_BOLD(RED)     LABEL_ERROR
#define WARN  COLOR_BOLD(YELLOW)  LABEL_WARN
#define DEBUG COLOR_BOLD(DEFAULT) LABEL_DEBUG COLOR_RESET

#endif // LABELS_H
